CONFIG_NAME: mainnet
PRESET_BASE: mainnet
TERMINAL_TOTAL_DIFFICULTY: "0"
TERMINAL_BLOCK_HASH: "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: "18446744073709551615"
SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY: "128"
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: "80"
MIN_GENESIS_TIME: "1688252390"
GENESIS_FORK_VERSION: "0x42424242"
GENESIS_DELAY: "180"
ALTAIR_FORK_VERSION: "0x01000000"
ALTAIR_FORK_EPOCH: "0"
BELLATRIX_FORK_VERSION: "0x02000000"
BELLATRIX_FORK_EPOCH: "0"
CAPELLA_FORK_VERSION: "0x03000000"
CAPELLA_FORK_EPOCH: "3"
SECONDS_PER_SLOT: "8"
SECONDS_PER_ETH1_BLOCK: "1"
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: "256"
SHARD_COMMITTEE_PERIOD: "256"
ETH1_FOLLOW_DISTANCE: "64"
INACTIVITY_SCORE_BIAS: "4"
INACTIVITY_SCORE_RECOVERY_RATE: "16"
EJECTION_BALANCE: "16000000000"
MIN_PER_EPOCH_CHURN_LIMIT: "4"
CHURN_LIMIT_QUOTIENT: "65536"
PROPOSER_SCORE_BOOST: "40"
DEPOSIT_CHAIN_ID: "8888"
DEPOSIT_NETWORK_ID: "8888"
DEPOSIT_CONTRACT_ADDRESS: "0x4242424242424242424242424242424242424242"
